//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Get_User", ReplyAction="http://tempuri.org/IService/Get_UserResponse")]
        System.Data.DataSet Get_User(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Get_User", ReplyAction="http://tempuri.org/IService/Get_UserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_UserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Get_Users", ReplyAction="http://tempuri.org/IService/Get_UsersResponse")]
        System.Data.DataSet Get_Users();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Get_Users", ReplyAction="http://tempuri.org/IService/Get_UsersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_UsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Insert_User", ReplyAction="http://tempuri.org/IService/Insert_UserResponse")]
        void Insert_User(MyWeb.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Insert_User", ReplyAction="http://tempuri.org/IService/Insert_UserResponse")]
        System.Threading.Tasks.Task Insert_UserAsync(MyWeb.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Delete_User", ReplyAction="http://tempuri.org/IService/Delete_UserResponse")]
        void Delete_User(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Delete_User", ReplyAction="http://tempuri.org/IService/Delete_UserResponse")]
        System.Threading.Tasks.Task Delete_UserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Update_User", ReplyAction="http://tempuri.org/IService/Update_UserResponse")]
        void Update_User(MyWeb.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Update_User", ReplyAction="http://tempuri.org/IService/Update_UserResponse")]
        System.Threading.Tasks.Task Update_UserAsync(MyWeb.ServiceReference1.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MyWeb.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MyWeb.ServiceReference1.IService>, MyWeb.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_User(int id) {
            return base.Channel.Get_User(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_UserAsync(int id) {
            return base.Channel.Get_UserAsync(id);
        }
        
        public System.Data.DataSet Get_Users() {
            return base.Channel.Get_Users();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_UsersAsync() {
            return base.Channel.Get_UsersAsync();
        }
        
        public void Insert_User(MyWeb.ServiceReference1.User user) {
            base.Channel.Insert_User(user);
        }
        
        public System.Threading.Tasks.Task Insert_UserAsync(MyWeb.ServiceReference1.User user) {
            return base.Channel.Insert_UserAsync(user);
        }
        
        public void Delete_User(int id) {
            base.Channel.Delete_User(id);
        }
        
        public System.Threading.Tasks.Task Delete_UserAsync(int id) {
            return base.Channel.Delete_UserAsync(id);
        }
        
        public void Update_User(MyWeb.ServiceReference1.User user) {
            base.Channel.Update_User(user);
        }
        
        public System.Threading.Tasks.Task Update_UserAsync(MyWeb.ServiceReference1.User user) {
            return base.Channel.Update_UserAsync(user);
        }
    }
}
